<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Articulos</title>
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
    <div class="contenedor">
        <h1>Articulos</h1>
        <section class="articulos">
            <ul>
                <?php foreach($articulos as $articulo): ?>
                    <li><?php echo $articulo['id'] . '.- ' . $articulo['titulo'] ?></li>
                <?php endforeach; ?>
            </ul>
        </section>
        <section class="paginacion">
            <ul>
                <!-- Establecemos cuando el boton de "anterior" estara deshabilitado -->
                <?php if($pagina == 1): ?>
                    <li class="disabled">&laquo;</li>
                <?php else: ?>
                    <li><a href="?pagina=<?php echo $pagina-1?>">&laquo;</a></li>
                <?php endif; ?>
                
                <!-- Ejecutamos un ciclo para mostrar las páginas -->
                <?php
                    for ($i=1; $i <= $numeroPaginas; $i++) { 
                        if($pagina==$i){
                            echo "<li class='active'><a href='?pagina=$i'>$i</a></li>";
                        } else {
                            echo "<li><a href='?pagina=$i'>$i</a></li>";
                        }
                    }
                ?>
                
                <!-- Establecemos cuando el boton de "siguiente" estara deshabilitado -->
                <?php if($pagina == $numeroPaginas): ?>
                    <li class="disabled">&raquo;</li>
                <?php else: ?>
                    <li><a href="?pagina=<?php echo $pagina+1?>">&raquo;</a></li>
                <?php endif; ?>
                
            </ul>
        </section>
    </div>
</body>
</html>
